CREATE TABLE Client(Id_Client SERIAL, First_Name VARCHAR(50) NOT NULL, Last_Name VARCHAR(50) NOT NULL, User_Name VARCHAR(50) NOT NULL, Email VARCHAR(255) NOT NULL, Password VARCHAR(255) NOT NULL, Role VARCHAR(50) NOT NULL, Status VARCHAR(50) NOT NULL, PRIMARY KEY(Id_Client), UNIQUE(User_Name), UNIQUE(Email));

